mezmo/terraform-provider-mezmo

internal/provider/destination_resource.go, internal/provider/processor_resource.go, internal/provider/source_resource.go
The JSON api model returns `http` for both http source and http sink making it difficult to identify conflicting resources.
This PR fixes it
=> feat: Make convertible resource typenames unique

examples/processors/parse_sequentially.tf, internal/provider/models/processors/parse.go, internal/provider/models/processors/parse_sequentially.go, internal/provider/models/processors/route.go, pkg/resources/convertible.go, pkg/resources/convertible_test.go, pkg/resources/testdata/compact_fields.json, pkg/resources/testdata/dedupe.json, pkg/resources/testdata/drop_fields.json, pkg/resources/testdata/flatten_fields.json, pkg/resources/testdata/map_fields.json, pkg/resources/testdata/parse.json, pkg/resources/testdata/parse_sequentially.json, pkg/resources/testdata/reduce.json, pkg/resources/testdata/route.json, pkg/resources/testdata/simple_route.json
ConvertToTerraformModel populates list fields as empty and object fields as null due to the absence of a Terraform state.
Models that retrieve the list item type or object type from the model object then fail.
To fix this, we need to check if the type is nil and retrieve it directly from the model's schema.
=> fix: Ensure processors can be converted to terraform model

go.mod, go.sum
This fixes an issue with terraform 1.6 client users potentially facing issues when running terraform plan or apply against our mezmo provider.
See: https://github.com/hashicorp/terraform-plugin-framework/issues/853
Ref: LOG-18456
=> fix(dependencies): Update terraform-plugin-framework to 1.4.1

Jenkinsfile
Set the build description with the sanity param value so that
it is easy to see which build is what from the CI list.
=> chore(ci): Set build desc with sanity param value

internal/provider/models/destinations/test/datadog_metrics_test.go, internal/provider/models/sources/test/agent_test.go
Cleaning up the cacheKey values used in some of the test cases to follow our testing guidelines.
Ref: LOG-18529
=> fix(test): clean up test cacheKey values

internal/provider/models/processors/reduce.go
The flush_condition block will always appear in the API response but should be ignored/disabled if the `when` child attribute is set to `none`. This commit corrects this logic by only attempting to parse the block for valid `when` values.
Ref: LOG-18549
=> fix(reduce): fix flush_condition parsing to read from when

internal/provider/models/processors/sample.go
When generating the internal config for the Sample processor, the service will skip the `always_include` block if it doesn't exist or if it doesn't contain a property named `field`:
```
const always_include = this.user_config.always_include
if (!always_include?.field) {
return
}
// additional processing ...
```
This change updates the provider to assume that it might get an `always_include` object which might be missing the `field` property.
Ref: LOG-18550
=> fix(sample): update how to parse API response

internal/provider/models/modelutils/operator_labels.go
We added support for a new not_contains operator in the service. This adds supports in the terraform provider.
Ref: LOG-18791
=> fix(operators):  Add not_contains to list of operators

Makefile
When using the `dev_overrides` block in terraform config, there is a warning that crops up everytime you run terraform. This removes that warning.
ref: LOG-18743
=> LOG-18743: squelch `dev_overrides` warnings

internal/provider/models/processors/base_parse_model.go, internal/provider/models/processors/test/parse_sequentially_test.go, internal/provider/models/processors/test/parse_test.go
The target_field of parse and parse sequential processors are optional. Remove the validation and add tests.
Issue was discovered during QA
Ref: [LOG-18805](https://mezmo.atlassian.net/browse/LOG-18805)
[LOG-18805]: https://mezmo.atlassian.net/browse/LOG-18805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Remove validation on  parse target_field

internal/provider/models/modelutils/conditional_types.go, internal/provider/models/modelutils/testdata/unwind_conditional.json
No value operators such as is_array, is_metric etc have value set to an empty string. value_string has a min length of 1 and this fails terraform plan.
Ref: LOG-18847
=> fix: Do not set string value for no value operators

internal/provider/models/destinations/datadog_logs.go, internal/provider/models/destinations/loki.go, internal/provider/models/destinations/test/datadog_logs_test.go, internal/provider/models/destinations/test/loki_test.go
Check empty string values before setting it back to the plan.
Ref: LOG-18731
=> fix: Optional strings in the plan

docs/resources/reduce_processor.md, internal/provider/models/processors/reduce.go, internal/provider/models/processors/test/reduce_test.go
Adds a new config parameter for reduce that allows users to specify the maximum number of events that a reduce operation can contain.
Ref: LOG-19036
=> chore(reduce):  Add max_events to provider for reduce processor

internal/provider/models/destinations/gcp_cloud_storage.go, internal/provider/models/destinations/test/gcp_cloud_storage_test.go
Previously, the GCP Cloud Storage destination would convert a nil to an empty string and cause validations against the upstream service. This adds some checks to the type before setting on the tf plan.
Ref: LOG-18742
=> fix(gcp): Fix setting bucket prefix only if it's not nil

internal/provider/models/processors/aggregate_v2.go, internal/provider/models/processors/test/aggregate_v2_test.go
Brings the aggregate-v2 model in the provider inline with the schema that has evolved from work in the API schema. Includes some refactoring to break apart the large FromModel conversion function into smaller parts.
Ref: LOG-19284
=> fix(aggregate-v2): Update provider model to match API schema

Jenkinsfile, Makefile, examples/processors/parse_sequentially.tf
This change un-swallows exit codes during example validation. As we were
piping the output to awk, the exit code of the docker command was lost.
Change the shell to bash, and use the PIPESTATUS variable to exit with
the same code as the docker command.
=> fix(ci): Don't swallow errors during example validation

Jenkinsfile, package-lock.json, package.json
This repo is public, and thus should enforce `commitlint` while protecting against public PRs running against CI without authorization.
Ref: LOG-19855
=> fix(ci): Update `Jenkinsfile` with public repo necessities

docs/resources/absence_alert.md, docs/resources/change_alert.md, docs/resources/threshold_alert.md, examples/resources/mezmo_absence_alert/resource.tf, examples/resources/mezmo_change_alert/resource.tf, examples/resources/mezmo_threshold_alert/resource.tf, internal/provider/models/alerts/absence.go, internal/provider/models/alerts/base_model.go, internal/provider/models/alerts/change.go, internal/provider/models/alerts/test/absence_test.go, internal/provider/models/alerts/test/change_test.go, internal/provider/models/alerts/test/threshold_test.go, internal/provider/models/alerts/threshold.go, pkg/resources/testdata/alerts/absence.json, pkg/resources/testdata/alerts/change.json, pkg/resources/testdata/alerts/threshold.json
This field name was changed to avoid confusion with event `.message` properties.
Ref: LOG-19914
=> fix(alerts): For `alert_payload`, change `message` to `body`

docs/resources/absence_alert.md, docs/resources/change_alert.md, docs/resources/threshold_alert.md, internal/provider/models/alerts/base_model.go
Alert `body` and `subject` can now use template styling.
Ref: LOG-20001
=> chore(alerts): Add `template` as a style

README.md, internal/provider/models/destinations/prometheus_remote_write.go, internal/provider/models/destinations/test/prometheus_remote_write_test.go
When changing the `ack_enabled` setting, the provider was not including the value in its call to the server. This bug resulted from a lack of proper testing. The test has been fixed.
This commit also updates the `README` for slightly clearer instructions for running the provider locally.
Ref: LOG-19994
=> fix(destinations): Prometheus destination doesn't repsect `ack_enabled`

Makefile
latest currently is v2, which is a breaking release.
refs: LOG-20051
=> fix: Use goreleaser v1.26.2 instead of latest

docs/resources/absence_alert.md, examples/resources/mezmo_absence_alert/resource.tf, internal/provider/models/alerts/absence.go, internal/provider/models/alerts/base_model.go, internal/provider/models/alerts/change.go, internal/provider/models/alerts/test/absence_test.go, internal/provider/models/alerts/threshold.go, pkg/resources/testdata/alerts/absence.json
The absence alert API schema no longer supports defining the `operation` or `script` fields. This commit updates the provider to match that requirement.
Ref: LOG-20049
=> fix(alert): Update absence alert resource to match API

.goreleaser.yml, Makefile
`goreleaser` just did a major release, eliminating the ability to install previous versions. This means all users will have to upgrade it for deployment. This commit fixes the configuration file according to: https://carlosbecker.com/posts/goreleaser-v2/
Ref: LOG-20064
=> fix: bump goreleaser@2.0.0

.gitignore, Makefile, docs/index.md, examples/provider/provider.tf
**fix(docs): Change provider version to 2.0.0 where needed**
The example for the provider itself specifies the version. That needs to
be upgraded to our latest major revision, or some components won't work.
Publish this release so that the Terraform registry docs are correct
with that version in the examples.
Ref: LOG-20006
---
**fix(examples): Specify goreleaser version**
When running `make examples` we should specify the version since a
recent upgrade forced changes to our configuration that are not backward
compatible. Also, silence the `@docker` command, but `@echo` the example
being validated.
Ref: LOG-20006
=> fix(docs): Change provider version to 2.0.0 where needed

docs/resources/route_processor.md, internal/provider/models/processors/route.go, internal/provider/models/processors/test/route_test.go
The WebUI allows for 255 characters so the provider should allow the same. This change bumps the limit from 20 characters on the label length to 255 and adds a test to verify that it is not exceeded.
Ref: LOG-20068
=> fix(route): Increase the character limit for route labels

docs/resources/publish_pipeline.md, examples/resources/mezmo_publish_pipeline/resource.tf, internal/client/types.go, internal/provider/models/publish_pipeline.go, internal/provider/publish_pipeline_resource.go, internal/provider/publish_pipeline_resource_test.go
Selectively publishing a pipeline doesn't really work in Terraform due to race conditions. The pipeline resources are updated atomically outside of the scope of `publish_pipeline`, therefore it's possible that states will update even if the publish command fails (paused pipeline, for example). This causes a situation where no changes are detected, and thus `publish_pipeline` does not become part of the `plan`.
To fix this, constantly remove the `publish_pipeline` from state every time `Read()` is called. This will force "re-creation" of the publish resource such that it will be executed every time. Since the `ENOCHANGES` error is ignored, this operation becomes idempotent.
BREAKING CHANGE: This removes the required `updated_at` property from the schema. Users will get an error if …
=> fix(resources)!: `publish_pipeline` should be re-created every time

docs/resources/shared_source.md, internal/client/types.go, internal/provider/models/shared_source.go, internal/provider/shared_source_resource_test.go
The `description` field for the shared_source resource should have been optional, not required.
Ref: LOG-20092
=> fix(resources): `shared_source` description should be optional

internal/provider/models/alerts/base_model.go
This value includes the Mezmo log analysis key and should be treated as a sensitive credential value.
Ref: LOG-20098
=> fix(alert): add sensitive flag to ingestion key field

internal/provider/models/alerts/absence.go, internal/provider/models/alerts/change.go, internal/provider/models/alerts/threshold.go
Updated functions that convert from an alert API response to the TF
models so they actually set the `component_id` and `component_kind`
fields.
Ref: LOG-20106
=> fix(alert): fix handling of component_id and component_kind

compose/base.yml, internal/provider/models/processors/test/aggregate_v2_test.go
This fixes an inconsistency that causes the service to fail to start.
Ref: LOG-20221
=> fix(test): use correct image/version for tsdb

Dockerfile, Makefile, internal/provider/models/processors/test/aggregate_v2_test.go, internal/provider/models/processors/test/unroll_test.go
The env variables was loaded for all targets causing the test-unit to run the acceptance tests as well.
Also make the docs test to only check the docs folder.
Ref: LOG-19481
=> ci: fix connection refused

docs/resources/absence_alert.md, docs/resources/change_alert.md, docs/resources/threshold_alert.md, examples/resources/mezmo_absence_alert/resource.tf, examples/resources/mezmo_change_alert/resource.tf, examples/resources/mezmo_threshold_alert/resource.tf, internal/provider/models/alerts/base_model.go
**fix(examples): New alert payload needs examples**
The examples were not updated after the alert payload changed.
Ref: LOG-20284
---
**fix(alerts): Mark sensitive fields after payload shape change**
The shape of the payload changed, and the `ingestion_key` was
re-defined, but not marked as `Sensitive`. This breaks the import/export
tool, and it should be marked sensitive anyway.
Ref: LOG-20284
=> fix(examples): New alert payload needs examples

Jenkinsfile, Makefile
This change splits the 3 test types (doc, unit, integration) into their
own stages for better parallelization and better visibility into which
type of test fails.
Ref: LOG-20344
=> chore(ci): Split test types into own stages

Makefile, docs/resources/absence_alert.md, docs/resources/change_alert.md, docs/resources/threshold_alert.md, examples/resources/mezmo_absence_alert/resource.tf
This change explicitly uses the derived GOOS and GOARCH values in this
targets docker command, instead of implicitly using them.
=> chore: Update snapshot binary make target

docs/resources/absence_alert.md, docs/resources/change_alert.md, docs/resources/threshold_alert.md, examples/resources/mezmo_absence_alert/resource.tf, internal/provider/models/alerts/base_model.go, internal/provider/models/alerts/test/threshold_test.go
When using a webhook alert destination, the resource now supports authentication types and user-defined request headers.
Ref: LOG-20388
=> feat(destinations): Add webhook options to alerts

docs/resources/absence_alert.md, docs/resources/change_alert.md, docs/resources/threshold_alert.md, examples/resources/mezmo_absence_alert/resource.tf, internal/provider/models/alerts/base_model.go, internal/provider/models/alerts/test/threshold_test.go
When using `webhook` to deliver alerts, the `method` option can be used to control the HTTP method.
Ref: LOG-20406
=> feat(alerts): Add `method` as a webhook channel option

docs/resources/absence_alert.md, docs/resources/change_alert.md, docs/resources/threshold_alert.md, internal/provider/models/alerts/base_model.go
Some of the properties in the alert schema were missing descriptions. Also, add wording (and doc link) for templates and how to use them.
Ref: LOG-20499
=> fix(docs): Update alert descriptions

docs/resources/shared_source.md, internal/client/types.go, internal/provider/models/shared_source.go, internal/provider/shared_source_resource_test.go
Add consumer_id to the shared source model, this ID is what can be used
to derive the endpoint for the shared source.
Ref: LOG-20980 #213
=> fix(shared-source): missing consumer_id

compose/base.yml
Required in order for `make test` to succeed.
Ref: LOG-21139
=> build: update timescale version used in tests

internal/provider/models/processors/trace_sampling.go
summary: set explicit fields to null when not expected by the type to appease state management
ref: LOG-21641
=> fix(sampling): set null fields

README.md, internal/provider/models/destinations/http.go, internal/provider/models/destinations/test/http_test.go
When creating a model from API state, auth fields depend on the strategy. When strategy is token, the user/password fields are absent. The new implementation ensures that an object attribute value error is not thrown.
=> fix: Fix error in http sink auth rehydration
